table DimGeography
	lineageTag: 2b1eef70-1dd9-42c6-9f28-1d57b2ab5ba1

	column Country
		dataType: string
		lineageTag: 3e752396-44c7-46c4-8d18-4e1499edbf8e
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column 'Population 2020'
		dataType: int64
		formatString: #,0
		lineageTag: f2686270-7163-43c7-9069-0904a5466d6d
		summarizeBy: sum
		sourceColumn: Population 2020

		annotation SummarizationSetBy = Automatic

	column 'Land Area Km2'
		dataType: double
		formatString: #,0
		lineageTag: 18303af4-a536-40dd-a45d-4027359b4d28
		summarizeBy: sum
		sourceColumn: Land Area Km2

		annotation SummarizationSetBy = Automatic

	column 'Density Per Km2'
		dataType: int64
		formatString: #,0
		lineageTag: 52ffd3ac-9222-446a-b14e-215487d64403
		summarizeBy: none
		sourceColumn: Density Per Km2

		annotation SummarizationSetBy = Automatic

	partition DimGeography = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Zenbook\Desktop\power-bi-projects\Social Media Sentiment Analysis\Sentiment Analysis Dataset\train.csv"), [Delimiter = ",", Columns = 10, Encoding = 1252, QuoteStyle = QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    SourceNames = Table.ColumnNames(PromotedHeaders),
				    MetricNames = List.LastN(SourceNames, 3),
				    SelectedColumns = Table.SelectColumns(PromotedHeaders, List.Combine({{"Country"}, MetricNames})),
				    RenamedColumns = Table.RenameColumns(SelectedColumns, List.Zip({MetricNames, {"Population 2020", "Land Area Km2", "Density Per Km2"}})),
				    TrimmedCountry = Table.TransformColumns(RenamedColumns, {{"Country", each Text.Trim(Text.From(_)), type text}}),
				    RemovedBlankKeys = Table.SelectRows(TrimmedCountry, each [Country] <> null and [Country] <> ""),
				    DistinctCountries = Table.Distinct(RemovedBlankKeys, {"Country"}),
				    ChangedType = Table.TransformColumnTypes(DistinctCountries, {{"Country", type text}, {"Population 2020", Int64.Type}, {"Land Area Km2", type number}, {"Density Per Km2", Int64.Type}}, "en-US"),
				    SortedRows = Table.Sort(ChangedType, {{"Country", Order.Ascending}})
				in
				    SortedRows

	annotation PBI_ResultType = Table
